### ISSUE TITLE
Images are now expiring and deleted on docker hub

### ISSUE THREAD

**Issue by AndrewSav** [mailserver2/mailserver#19]
#### Classification

* [X] Question
* [X] Deliverability issue

#### Reproducibility

* [X] Not applicable

#### Description
Docker now deletes images that have not been pushed or pulled for 6 months. Does this affect us, and if yes, should we do anything about it?

**Comment by sknight80** [comment]
I don't think so, because we have our own docker repo where we pushed our image within a month or two.  I have a branch where I am going to update our base image with a newer version.

**Comment by AndrewSav** [comment]
But the nature of the project is so, that it gets pushed when someone gets around to doing it, that is if everyone is busy no one will make the push. It's not like we have a release schedule or something. Hence the question.

**Comment by sknight80** [comment]
Yeah, you have a point. But if we do image update at least once a month, then we should be good, am I right?

**Comment by AndrewSav** [comment]
Sure, but image update once a month is not a guarantee or a promise. It may not happen.

**Comment by ThibaultVlacich** [comment]
Btw, https://github.com/mailserver2/mailserver/releases/tag/v1.1.3 that has been tagged ~10 days ago as not been pushed to Docker Hub.

**Comment by AndrewSav** [comment]
Hey, @sknight80, I think the idea was to tag and push at about the same time. Is there any problem here I can help with?

**Comment by sknight80** [comment]
@AndrewSav yeah, that was the idea, but I think I messed up. :/ (I did it the first time, and I wasn't sure if I did it right.  Looks like not.). @SaraSmiseth pointed out this problem: https://github.com/mailserver2/mailserver/pull/20#issuecomment-696834088

**Comment by AndrewSav** [comment]
I'm closing this because I think we have discussed it sufficiently and it does not appear that there is anything we need to do.
