### ISSUE TITLE
outgoing mail problem without dkim signature

### ISSUE THREAD

**Issue by epa64** [mailserver2/mailserver#28]
hi,
I am on version 1.1-stable mailserver.
I haven't migrated yet because is in production since two years.
I am some problem with smtp i losed the dkim signature on outgoing mail.
I think is after i add the multimap.
somebody can help me?
best regard's

**Comment by AndrewSav** [comment]
Could you please provide steps to reproduce with as much details as possible.

**Comment by arnauvp** [comment]
Hey, it seems we are also experiencing this. We just realized… and we recently added a multimap too, for spam whitelist.

Need to confirm it, will report back when I know more.

**Comment by epa64** [comment]
Hi,

yes i add white domain list.

it's work fine.


Best regards

Le 26/11/2020 à 15:41, Arnau VP a écrit :

**Comment by AndrewSav** [comment]
@epa64 is your issue resolved?

**Comment by arnauvp** [comment]
I was able to reproduce the issue.

We recently added both

`"WHITELIST_SPAM_ADDRESSES=one@example.com,two@example.com,three@example.com"`

and
```
# `config/mail/rspamd/multimap.conf`
SENDER_FROM_WHITELIST_USER {
  type = "from";
  filter = "email:addr";
  map = "/etc/rspamd/local.d/whitelist.sender.map";
  action = "accept"; # Prefilter mode
}
```

the map is a list:
```
one@example.com
two@example.com
three@example.com
```

It seems the latter is the one that disables DKIM signing for all users at example.com (not only on the map), even though on startup:
```
[INFO] Found DKIM key pair for domain example.com - skip creation
[INFO] DKIM/ARC signing is enabled
```

**Comment by arnauvp** [comment]
@AndrewSav do you think the above is a misconfiguration? Or is it a bug that DKIM signing is disabled once SENDER_FROM_WHITELIST_USER is defined as above?

**Comment by AndrewSav** [comment]
@arnauvp Do you think it's an rspamd bug / misconfiguration? There are probably rspamd documentation/support forums that could help? I googled a bit and some people in different config relation situations suggest running `rspamadm configtest` to make sure consistency of the configuration, can you try that?

**Comment by arnauvp** [comment]
OK so it seems we have figured it out. Once prefilter is configured, all normal prefilter flows are skipped, so for users in our whitelist the DKIM step was not done (and not all users as thought initially).

We have instead configured the map in ratelimit.conf as such:

`whitelisted_user = "/etc/rspamd/local.d/whitelist.sender.map";`

**Comment by arnauvp** [comment]
It seems I can't close the issue myself. @AndrewSav would you mind doing so?

**Comment by diroots** [comment]
hello here. after tests of the white list multimap rule, with action = "accept"; # Prefilter mode

this is the prefilter mode which bypass all subsequent filters of rspamd. 

to correctly whitelist users, but keep the DKIM signing step to be applied, one must not use multimap with the action prefilter mode. 

if the whitelist goal is to bypass the rate limiting, the whitelisted_user param pointing to a map of users (one per line) is to be used in the ratelimit plugin config file, not in the multimap one.  as per documentation here : https://rspamd.com/doc/modules/ratelimit.html
