### ISSUE TITLE
Implement Security Update for Dovecot v2.3.12 

### ISSUE THREAD

**Issue by PhilipSchillmaier** [mailserver2/mailserver#30]
#### Classification

* [X] Vulnerability

#### Reproducibility

* [X] Always

#### Docker information
```
docker info
docker images mailserver2/mailserver --digests --filter "dangling=false"
```
```
REPOSITORY               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
mailserver2/mailserver   1.1.5               sha256:18d98b8d6601ebae76d6f90aae5e5858cf29b5b7fd6c92f698e6294eee17f6f6   23a3e3b84fee        5 weeks ago         314MB
mailserver2/mailserver   latest              sha256:18d98b8d6601ebae76d6f90aae5e5858cf29b5b7fd6c92f698e6294eee17f6f6   23a3e3b84fee        5 weeks ago         314MB
```

#### Description
Dovecot provided an security update
https://dovecot.org/pipermail/dovecot-news/2021-January/000448.html

Please update the docker image accordingly.

#### Steps to reproduce
1. Start mailserver2 container
2. ```docker exec -it mailserver_mailserver_1 dovecot --version```

#### Expected results
2.3.13

#### Actual results
2.3.4.1

**Comment by SaraSmiseth** [comment]
The latest version from the [debian repository](https://packages.debian.org/buster/dovecot-core) is still 2.3.4.1.

@AndrewSav @sknight80 
Should we use the [dovecot repository](https://doc.dovecot.org/installation_guide/dovecot_community_repositories/debian_packages/) instead?

**Comment by neuffer** [comment]
The latest version from the Debian repository is the bullseye version 1:2.3.11.3+dfsg1-2:
https://packages.debian.org/bullseye/dovecot-core

**Comment by sknight80** [comment]
@SaraSmiseth if we got the most recent update for dovecot I don't see the problem with that.  However when we have a new Debian version maybe we should switch to it.

**Comment by AndrewSav** [comment]
My preference is to stay on Debian repo, as I do not what to add one more thing that can potentially break and make it more fragile. If we decide to stay on Debian we will have to wait until their repo gets the fix before we can do anything about this. On the other hand if anyone is in a hurry and wants to submit a PR, I'll help reviewing it.

We should not go to Bullseye until it's released.

**Comment by SaraSmiseth** [comment]
Yes Bullseye is still testing and not stable.

**Comment by jinks** [comment]
Keep in mind that Debian backports security fixes to stable, so the version number alone isn't a good indicator.

Also, this is 2 months old now, does it need to stay open?

**Comment by AndrewSav** [comment]
When Bullseye releases we will endeavour to upgrade to it, hopefully resolving the original issue in the process @jinks.
