### ISSUE TITLE
Update dovecot version to 2.3.20

### ISSUE THREAD

**Issue by akhil1508** [mailserver2/mailserver#49]
#### Classification

* [ X] Feature/Enhancement

#### Reproducibility
_Please delete options that are not relevant._

* [X] Always
* 
#### Docker information
```
docker info
docker images mailserver2/mailserver --digests --filter "dangling=false"
```

#### Description
Dovecot 2.3.14 onwards supports stuff like environment variables in config. We are still using 2.3.13 over here. I think we can update the image to 2.3.20 which is the latest stable version.
- I see it uses debian and apt-get to install so the version is coming from there.
  - Perhaps we add dovecot repositories that have latest version to handle this?

**Comment by ksylvan** [comment]
Closing this. The latest `mailserver2/mailserver` image incorporates dovecot-2.3.19 and will keep updating as the base Debian image is updated. We want the most stable and tested together package sets.
