### ISSUE TITLE
Migration from hardware/mailserver

### ISSUE THREAD

**Issue by pollux** [mailserver2/mailserver#8]
#### Classification
* [X] Question

#### Description
I personally have no deeper knowledge of docker, docker images and so on. So the answer to my question might seem very easy and logic to others, but for me its a thing:

How do i migrate from the hardware/mailserver to this fork? Are there any mentionable 
hints? Or is it just painless by removing the old images and pulling the new ones from the docker hub?

**In general: What needs to be taken care of when migrating?**

**Comment by SaraSmiseth** [comment]
I wrote a wiki page: https://github.com/mailserver2/mailserver/wiki/Migration-from-hardware-mailserver.

**Comment by AndrewSav** [comment]
The wiki page says:

> There is only a latest tag for now. Change MAILSERVER_DOCKER_TAG to latest

Generally this is a Bad Idea. [Friends don't let friends](https://twitter.com/mattfarina/status/1067815312295256064) [use latest](https://github.com/containous/traefik/issues/6062#issuecomment-567126469).

I suggest we tag it properly and update the wiki. 

We can tag it either as 1.1.1 or 1.2.0, I suggest we never push the same version to docker hub once it's there and keep incrementing them as we release new version. We also tag the repo when we do a release.

This give the user the precise control over what exactly they are running. This is a good practice.

**Comment by sknight80** [comment]
I like the idea to using versions.  In that case, we can roll back to the previous version with no problem.  Unless there was a DB change that will not work on the previous version.  But I think we can mention that in the changelog.

**Comment by AndrewSav** [comment]
It looks like this is answered. Please, comment or re-open if not.

**Comment by epa64** [comment]
hi,
I am on version 1.1-stable mailserver.
 I haven't migrated yet because is in production since two years.
I am some problem with smtp i losed the dkim signature on outgoing mail.
I think is after i add the multimap.
somebody can help me?
best regard's

**Comment by epa64** [comment]
sorry,
i made a mistake.
I wanted to create a new request
