### ISSUE TITLE
Initial coordination of maintenance efforts

### ISSUE THREAD

**Issue by AndrewSav** [mailserver2/mailserver#9]
Since we have trouble finding online chat platform that we are all comfortable to use, this thread is for fleshing out the initial coordination of sustaining this new repo.

This carries over from [this thread](https://github.com/hardware/mailserver/issues/418#issuecomment-639103779)

https://discord.gg/nb8tRGs
[#mailserver:matrix.org](https://github.com/hardware/mailserver/issues/418#issuecomment-552424199)

**Comment by AndrewSav** [comment]
One thing that comes to mind, is that we probably should issues some kind of statement on the status of this repo.

It seems that we are happy to run it in a "maintenance mode" rather than something that is being actively developed. I think this should be reflected in main readme page.

It probably not worth migrating old Wiki pages, because they are not going anywhere. We can migrate them on as needed basis if we need to make changes to them.

There is also https://github.com/hardware/nsd-dnssec that we have not brought over. If no one is going to that, we need to make a note of that too.

Thoughts?

**Comment by SaraSmiseth** [comment]
> One thing that comes to mind, is that we probably should issues some kind of statement on the status of this repo.
>
> It seems that we are happy to run it in a "maintenance mode" rather than something that is being actively developed. I think this should be reflected on the main readme page.

Yes. Good idea. I'll update the readme and create a PR.

> It's probably not worth migrating old Wiki pages, because they are not going anywhere. We can migrate them on as needed basis if we need to make changes to them.

I already copied the complete wiki. The only change I made is the new page about migrating to mailserver2.

> There is also https://github.com/hardware/nsd-dnssec that we have not brought over. If no one is going to do that, we need to make a note of that too.

I just found https://github.com/mxserver. There is an updated https://github.com/mxserver/nsd-dnssec.

**Comment by sknight80** [comment]
Awesome! Good Idea. I also joined the Discord server with one of my old accounts (mytesladream) and with a new one (s_knight). You can find me there too!

**Comment by AndrewSav** [comment]
When I ran `make`, it does not produce working images. This is what I'm getting:

https://gist.github.com/AndrewSav/c47a9355c5e135224a4faaf7fc7cd31b

Any ideas?

**Comment by AndrewSav** [comment]
Guys, I noticed that in docker hub some images got updated "a day ago".

Without versioning as suggested above and without any change notes it's quite confusing and unsustainable.

Can we agree on a versioning scheme, and agree to always put release notes when an image is updated to a new version?
